name: Auto Comment Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Exécute le job toutes les heures
  push:
    branches:
      - main  # ou votre branche par défaut

jobs:
  update-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Mis à jour pour Node.js 16 et 20

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name 'Your Name'  # Remplacez par votre nom
          git config --global user.email 'your.email@example.com'  # Remplacez par votre email
          git remote set-url origin git@github.com:christ972/android_challenge.git  # Utilisation de SSH

      - name: Pull latest changes
        run: git pull origin main  # ou votre branche par défaut

      - name: Add comment
        run: |
          echo "// Temporary comment" >> temp_comment.txt
          cat temp_comment.txt >> file.txt  # Ajustez le chemin et le fichier en conséquence

      - name: Commit changes
        run: |
          git add .
          git commit -m "Add temporary comment"

      - name: Fetch latest changes again
        run: git fetch origin main  # ou votre branche par défaut

      - name: Merge changes
        run: git merge origin/main  # ou votre branche par défaut

      - name: Push changes
        run: |
          git push origin main  # ou votre branche par défaut
